name: Run Data Processing Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install pandas pytest  # ✅ Ensure pytest is installed

      - name: Run Data Processing Script
        run: python main.py  # ✅ Execute your main script

      - name: Run Tests
        run: python -m pytest test_main.py  # ✅ Run pytest using Python module
